# Generated by Django 3.1.6 on 2021-02-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='status',
            field=models.CharField(choices=[('w', 'waiting for check-in'), ('i', 'in building'), ('c', 'checked_out')], default='w', max_length=30),
        ),
    ]
