# Generated by Django 3.1.6 on 2021-02-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_visitor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
